// Map country/language names to flag emojis
const countryToFlag: Record<string, string> = {
  // Countries
  'japan': '🇯🇵',
  'japans': '🇯🇵',
  'portugal': '🇵🇹',
  'portugees': '🇵🇹',
  'brazilië': '🇧🇷',
  'braziliaans': '🇧🇷',
  'denemarken': '🇩🇰',
  'deens': '🇩🇰',
  'noorwegen': '🇳🇴',
  'noors': '🇳🇴',
  'zweden': '🇸🇪',
  'zweeds': '🇸🇪',
  'finland': '🇫🇮',
  'fins': '🇫🇮',
  'duitsland': '🇩🇪',
  'duits': '🇩🇪',
  'frankrijk': '🇫🇷',
  'frans': '🇫🇷',
  'spanje': '🇪🇸',
  'spaans': '🇪🇸',
  'italië': '🇮🇹',
  'italiaans': '🇮🇹',
  'griekenland': '🇬🇷',
  'grieks': '🇬🇷',
  'rusland': '🇷🇺',
  'russisch': '🇷🇺',
  'china': '🇨🇳',
  'chinees': '🇨🇳',
  'mandarijn': '🇨🇳',
  'korea': '🇰🇷',
  'koreaans': '🇰🇷',
  'zuid-korea': '🇰🇷',
  'india': '🇮🇳',
  'hindi': '🇮🇳',
  'arabisch': '🇸🇦',
  'saoedi-arabië': '🇸🇦',
  'turkije': '🇹🇷',
  'turks': '🇹🇷',
  'nederland': '🇳🇱',
  'nederlands': '🇳🇱',
  'belgië': '🇧🇪',
  'ijsland': '🇮🇸',
  'ijslands': '🇮🇸',
  'ierland': '🇮🇪',
  'iers': '🇮🇪',
  'gaelic': '🇮🇪',
  'schotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'schots': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'welsh': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'engeland': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'engels': '🇬🇧',
  'verenigd koninkrijk': '🇬🇧',
  'hawaii': '🇺🇸',
  'hawaïaans': '🇺🇸',
  'amerika': '🇺🇸',
  'amerikaans': '🇺🇸',
  'canada': '🇨🇦',
  'mexico': '🇲🇽',
  'mexicaans': '🇲🇽',
  'argentinië': '🇦🇷',
  'chili': '🇨🇱',
  'peru': '🇵🇪',
  'colombia': '🇨🇴',
  'indonesië': '🇮🇩',
  'indonesisch': '🇮🇩',
  'maleisië': '🇲🇾',
  'maleis': '🇲🇾',
  'thailand': '🇹🇭',
  'thais': '🇹🇭',
  'vietnam': '🇻🇳',
  'vietnamees': '🇻🇳',
  'filipijnen': '🇵🇭',
  'filipijns': '🇵🇭',
  'tagalog': '🇵🇭',
  'polen': '🇵🇱',
  'pools': '🇵🇱',
  'tsjechië': '🇨🇿',
  'tsjechisch': '🇨🇿',
  'hongarije': '🇭🇺',
  'hongaars': '🇭🇺',
  'roemenië': '🇷🇴',
  'roemeens': '🇷🇴',
  'oekraïne': '🇺🇦',
  'oekraïens': '🇺🇦',
  'egypte': '🇪🇬',
  'egyptisch': '🇪🇬',
  'marokko': '🇲🇦',
  'marokkaans': '🇲🇦',
  'zuid-afrika': '🇿🇦',
  'afrikaans': '🇿🇦',
  'kenia': '🇰🇪',
  'swahili': '🇰🇪',
  'ethiopia': '🇪🇹',
  'amhaars': '🇪🇹',
  'nigeria': '🇳🇬',
  'ghana': '🇬🇭',
  'senegal': '🇸🇳',
  'tanzania': '🇹🇿',
  'australië': '🇦🇺',
  'nieuw-zeeland': '🇳🇿',
  'maori': '🇳🇿',
  'hebreeuws': '🇮🇱',
  'israël': '🇮🇱',
  'perzisch': '🇮🇷',
  'iran': '🇮🇷',
  'farsi': '🇮🇷',
  'pakistan': '🇵🇰',
  'urdu': '🇵🇰',
  'bangladesh': '🇧🇩',
  'bengaals': '🇧🇩',
  'sri lanka': '🇱🇰',
  'singalees': '🇱🇰',
  'tamil': '🇱🇰',
  'nepal': '🇳🇵',
  'tibetaans': '🇨🇳',
  'mongools': '🇲🇳',
  'mongolië': '🇲🇳',
  'kazachstan': '🇰🇿',
  'oezbekistan': '🇺🇿',
  'georgië': '🇬🇪',
  'georgisch': '🇬🇪',
  'armeens': '🇦🇲',
  'armenië': '🇦🇲',
  'servië': '🇷🇸',
  'servisch': '🇷🇸',
  'kroatië': '🇭🇷',
  'kroatisch': '🇭🇷',
  'slovenië': '🇸🇮',
  'sloveens': '🇸🇮',
  'oostenrijk': '🇦🇹',
  'zwitserland': '🇨🇭',
  'luxemburg': '🇱🇺',
  'letland': '🇱🇻',
  'lets': '🇱🇻',
  'litouwen': '🇱🇹',
  'litouws': '🇱🇹',
  'estland': '🇪🇪',
  'ests': '🇪🇪',
  'sanskriet': '🇮🇳',
  'latijn': '🇻🇦',
  'yiddisch': '🇮🇱',
  'inuit': '🇨🇦',
  'inuktitut': '🇨🇦',
  'navajo': '🇺🇸',
  'cherokee': '🇺🇸',
  'quechua': '🇵🇪',
  'guarani': '🇵🇾',
  'maya': '🇲🇽',
  'azteken': '🇲🇽',
  'nahuatl': '🇲🇽',
};

export function getCountryFlag(country: string): string {
  const normalized = country.toLowerCase().trim();

  // Direct match
  if (countryToFlag[normalized]) {
    return countryToFlag[normalized];
  }

  // Partial match - check if any key is contained in the country string
  for (const [key, flag] of Object.entries(countryToFlag)) {
    if (normalized.includes(key) || key.includes(normalized)) {
      return flag;
    }
  }

  // Default globe emoji if no match found
  return '🌍';
}
